language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -U flake8
  - pip install -U isort
  - pip install -U yapf

# command to run tests
script:
  - python manage.py test
  - find . -not -path '*/.eggs/*' -not -path './venv/*' -name '*.py' | xargs flake8
env:
  - Flask=0.12.2
